print("Tienda XYZ".center(30))
print("="*30)
print("Artículo\tCantidad\tPrecio")
print("Manzanas\t2kg\t\t$3.00")
print("Pan\t\t1\t\t$1.50")
print("Leche\t\t1L\t\t$0.99")
print("-"*30)
print("Total:\t\t\t\t$5.49")
